server:
  name: "mq-consumer"
  mode: "debug"
  metrics_port: "9093"

mysql:
  dsn: "" # 推荐通过环境变量 SECKILL_MYSQL_DSN 注入

mq:
  url: "" # 推荐通过环境变量 SECKILL_MQ_URL 注入

redis:
  addr: "localhost:6379"
  password: "123456"
  db: 0

#预备用到了Etcd或其他配置
etcd:
  addr: "127.0.0.1:2379"