server:
  name: "order-service"
  port: "50052"
  metrics_port: "9092"
  mode: "debug"

mysql:
  dsn: "" # 推荐通过环境变量 SECKILL_MYSQL_DSN 注入

mq:
  url: "" # 推荐通过环境变量 SECKILL_MQ_URL 注入

redis:
  addr: "localhost:6379"
  password: "123456"
  db: 1

etcd:
  addr: "127.0.0.1:2379"

seckill:
  purchase_limit: 5 #配置限购件数

jwt:
  expire: "5s"

grpc_client:
  product_service: "localhost:50051"