syntax = "proto3";

package order;

//指定生成go代码的目录
option go_package = "./common/pb;pb";

//下单请求
message CreateOrderRequest {
  int64 user_id = 1;
  int64 product_id = 2;
  int32 count = 3; // 购买数量
}

//下单响应
message CreateOrderResponse {
  string order_id = 1; // 订单号
  bool success = 2;
  string message = 3;
}

// 查询订单请求
message GetOrderRequest {
  string order_id = 1;
  int64 user_id = 2;
}

// 查询订单响应
message GetOrderResponse {
  bool found = 1;
  string order_id = 2;
  int64 user_id = 3;
  int64 product_id = 4;
  int32 count = 5;
  float amount = 6;
  int32 status = 7;
  string status_text = 8;
  string message = 9;
}

//定义服务
service OrderService {
  rpc CreateOrder(CreateOrderRequest) returns (CreateOrderResponse);
  rpc GetOrder(GetOrderRequest) returns (GetOrderResponse);
}
